### ISSUE TITLE
null reference in MyAssemblyInfo.ProcessMemberNode

### ISSUE THREAD

**Issue by sakno** [marek-stoj/ImmDoc.NET#1]
I caught the following exception when the file is processed with the documentation:

```
Unhandled exception: System.NullReferenceException:    
at Imm.ImmDocNetLib.MyReflection.MetaClasses.MyAssemblyInfo.ProcessMemberNode(XPathNavigator memberNodeNavigator, XPathNavigator docNavigator)
at Imm.ImmDocNetLib.MyReflection.MetaClasses.MyAssemblyInfo.ReadXmlDocumentation(String xmlDocPath)
at Imm.ImmDocNetLib.AssembliesInfo.ReadMyAssemblyInfoFromXmlDocumentation(String xmlDocPath)
at Imm.ImmDocNet.Program.ProcessFilesNames(List`1 filesNames)
at Imm.ImmDocNet.Program.Main(String[] args)
```

Version ImmDoc.NET 1.0.5.0. downloaded from [codeplex](http://immdocnet.codeplex.com/releases/view/57048).

If it is necessary, I can send my XML documentation to you.

**Comment by marek-stoj** [comment]
Thanks for the report - it'd be great if you could provide this XML documentation so that I can reproduce this issue.

**Comment by sakno** [comment]
It is located [here](http://cloud.github.com/downloads/sakno/DynamicScript/beta5-bin.zip).

**Comment by yallie** [comment]
@sakno Do you still have an XML file to reproduce this error?
XML file from beta6-bin.zip is processed without exceptions.
